# .pages.yml - Configuration PagesCMS pour Poitiers Collectif
settings:
  title: "Poitiers Collectif - Admin"
  description: "Interface d'administration pour le site Poitiers Collectif"
  logo: "/images/logo.png"

# Configuration des médias
media:
  input: static/images
  output: /images

# Collections de contenu
content:
  # Articles/Posts
  - name: articles
    label: "Articles"
    description: "Articles et actualités de Poitiers Collectif"
    type: collection
    path: content/posts
    format: yaml-frontmatter

    fields:
      - name: title
        label: "Titre"
        type: string
        required: true
        
      - name: author
        label: "Auteur"
        type: select
        required: true
        options:
          values : ["Poitiers Collectif", "Équipe municipale", "Contributeur externe"]
        default: "Poitiers Collectif"
        
      - name: date
        label: "Date de publication"
        type: date
        required: true
        options: 
          format: dd-MM-yyyy
        
      - name: lastmod
        label: "Dernière modification"
        type: date
        options: 
          format: dd-MM-yyyy
        
      - name: slug
        label: "URL (slug)"
        type: string
        description: "URL personnalisée pour l'article (optionnel)"
        
      - name: categories
        label: "Catégories"
        type: select
        options:
          multiple: true
          values : ["Actualités", "Politique"]
        
      - name: tags
        label: "Tags"
        type: string
        description: "Mots-clés libres pour l'article"
        
      - name: draft
        label: "Brouillon"
        type: boolean
        default: false
        description: "Article en cours de rédaction"
        
      - name: featured_image
        label: "Image mise en avant"
        type: image
        description: "Image principale de l'article"
        
      - name: summary
        label: "Résumé"
        type: text
        description: "Court résumé affiché dans les listes d'articles"
        
      - name: body
        label: "Contenu"
        type: rich-text
        required: true

  # Événements
  - name: evenements
    label: "Événements"
    description: "Événements et rendez-vous"
    type: collection
    path: content/evenements
    format: yaml-frontmatter
    fields:
      - name: title
        label: "Titre de l'événement"
        type: string
        required: true
        
      - name: date_event
        label: "Date de l'événement"
        type: date
        required: true
        options: 
          format: dd-MM-yyyy
        
      - name: date_end
        label: "Date de fin"
        type: date
        options: 
          format: dd-MM-yyyy
        
      - name: location
        label: "Lieu"
        type: string
        
      - name: address
        label: "Adresse complète"
        type: text
        
      - name: organizer
        label: "Organisateur"
        type: string
        default: "Poitiers Collectif"
        
      - name: categories
        label: "Type d'événement"
        type: select
        options:
          multiple: true
          values : ["Réunion publique", "Conseil municipal"]
        
      - name: registration_required
        label: "Inscription obligatoire"
        type: boolean
        default: false
        
      - name: registration_link
        label: "Lien d'inscription"
        type: string
        
      - name: image
        label: "Image de l'événement"
        type: image
        
      - name: description
        label: "Description courte"
        type: text
        description: "Description affichée dans la liste des événements"
        
      - name: body
        label: "Description détaillée"
        type: rich-text

  # Pages statiques
  - name: pages
    label: "Pages"
    description: "Pages statiques du site"
    type: collection
    path: content
    format: yaml-frontmatter
    fields:
      - name: title
        label: "Titre de la page"
        type: string
        required: true
        
      - name: description
        label: "Description"
        type: text
        description: "Description pour le SEO"
        
      - name: layout
        label: "Template"
        type: select
        options:
          multiple: true
          values : ["default", "page"]
        default: "page"
        
      - name: menu
        label: "Menu principal"
        type: boolean
        default: false
        description: "Afficher dans le menu principal"
        
      - name: weight
        label: "Ordre dans le menu"
        type: number
        description: "Ordre d'affichage (plus petit = plus haut)"
        
      - name: body
        label: "Contenu"
        type: yaml-frontmatter
        required: true