- name: articles
  label: "Articles"
  description: "Articles et actualités de Poitiers Collectif"
  type: collection
  path: content/posts
  format: md
  create: true
  delete: true

  fields:
    - name: title
      label: "Titre"
      type: string
      required: true
      
    - name: author
      label: "Auteur"
      type: select
      required: true
      options:
        - "Poitiers Collectif"
        - "Équipe municipale"
        - "Contributeur externe"
      default: "Poitiers Collectif"
      
    - name: date
      label: "Date de publication"
      type: datetime
      required: true
      format: "YYYY-MM-DDTHH:mm:ss"
      
    - name: categories
      label: "Catégories"
      type: select
      multiple: true
      options:
        - "Actualités"
        - "Politique"
        - "Culture" 
        - "Environnement"
        - "Social"
        - "Économie"
        - "Urbanisme"
        - "Transport"
        - "Éducation"
        - "Sport"
      
    - name: tags
      label: "Tags"
      type: list
      description: "Mots-clés libres pour l'article"
      
    - name: draft
      label: "Brouillon"
      type: boolean
      default: false
      
    - name: body
      label: "Contenu"
      type: markdown
      required: true